#ifndef __ESP_ALL_H__
#define __ESP_ALL_H__
#include <Arduino.h>
#include "esp_err.h"
#include "esp_camera.h"
#include "esp_log.h"
#include "esp_vfs_fat.h"
#include "esp_vfs.h"
#include "esp_wifi.h"
#include "esp_bt.h"
#include "esp_system.h"
#include "esp_heap_caps.h"
#include "esp_event.h"
#include "nvs_flash.h"
#include "driver/sdmmc_host.h"
#include "sdmmc_cmd.h"
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "freertos/queue.h"
#include "freertos/event_groups.h"
#include "esp_spiffs.h"
#include "esp_timer.h"
#include "SD_MMC.h"
#endif  // __ESP_ALL_H__