idf_component_register(
    SRCS
        "main.cpp"
        "init.cpp"
        "wifi.cpp"
        "process.cpp"
        "model_loader.cpp"
        "deep_sort.cpp"
        "semantic_seg.cpp"
        "collision.cpp"
        "image_filters.cpp"
    INCLUDE_DIRS
        "."
        "../components"
        "../include"

    REQUIRES
        esp32-camera
        esp_http_server
        esp_https_ota
        driver
        freertos
        nvs_flash
        sdmmc
        json
        mbedtls
        tflite-micro
        esp_timer
        esp_wifi
        fatfs
        esp-dl
        pthread
)
