; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html


[env:esp32cam]
platform = espressif32
board = esp32cam
monitor_speed = 115200
framework = arduino
board_build.filesystem = spiffs
board_build.arduino.psram_type = opi
monitor_filters = esp32_exception_decoder

build_flags =
    ; 基本配置
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
    -DCORE_DEBUG_LEVEL=5
    
    ; 简化PSRAM配置
    -D CONFIG_ESP32_SPIRAM_SUPPORT=y
    
    ; 简化内存分配配置
    -D CONFIG_SPIRAM_MALLOC_ALWAYSINTERNAL=16384
    -D CONFIG_SPIRAM_MALLOC=y
    
    ; 相机配置
    -D CAMERA_MODEL_AI_THINKER
    
lib_deps =
    spaziochirale/Chirale_TensorFLowLite @ ^2.0.0
