name: ESP32 Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 检出代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 设置 ESP-IDF 环境
      - name: Install ESP-IDF
        run: |
          mkdir -p $HOME/esp
          cd $HOME/esp
          git clone -b v5.1 --recursive https://github.com/espressif/esp-idf.git
          cd esp-idf
          ./install.sh esp32
          echo "IDF_PATH=$HOME/esp/esp-idf" >> $GITHUB_ENV

      # 安装依赖
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-opencv
          mkdir -p firmware/components
          git clone https://github.com/espressif/esp32-camera.git firmware/components/esp32-camera
          git clone --recursive https://github.com/espressif/esp-tflite-micro.git firmware/components/tflite-lib
          git clone https://github.com/espressif/esp-dl.git firmware/components/esp-dl

      # 编译项目
      - name: Build project
        run: |
          source $HOME/esp/esp-idf/export.sh
          cd firmware
          idf.py build

      # 保存构建产物
      - name: Save build directory
        run: |
          mkdir -p /tmp/firmware
          cp -r firmware/build/* /tmp/firmware/
          echo "Build artifacts saved to /tmp/firmware"
