name: ESP32 Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install ESP-IDF dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git wget flex bison gperf python3-pip python3-setuptools cmake ninja-build ccache libffi-dev libssl-dev dfu-util libusb-1.0-0 python3-opencv

      - name: Set up ESP-IDF
        run: |
          mkdir -p $HOME/esp
          cd $HOME/esp
          git clone --depth 1 https://github.com/espressif/esp-idf.git
          cd esp-idf
          ./install.sh esp32
        env:
          IDF_TOOLS_PATH: $HOME/.espressif

      - name: Add ESP-IDF to PATH
        run: echo "$HOME/esp/esp-idf/export.sh" >> $GITHUB_ENV

      - name: Prepare components
        run: |
          mkdir -p firmware/components
          cd firmware/components
          git clone https://github.com/espressif/esp32-camera.git esp32-camera
          git clone -b release/v1.0 https://github.com/espressif/esp-dl.git esp-dl
          git clone https://github.com/tensorflow/tflite-micro.git tflite-micro

      - name: Build project
        run: |
          source $HOME/esp/esp-idf/export.sh
          cd firmware
          idf.py set-target esp32
          idf.py -DSDKCONFIG_DEFAULTS="sdkconfig.defaults" -DPARTITION_TABLE_CSV_PATH="partitions.csv" build

      - name: Upload firmware binaries
        if: success()
        uses: actions/upload-artifact@v2
        with:
          name: firmware-binaries
          path: |
            firmware/build/*.bin
            firmware/build/bootloader/*.bin
            firmware/build/partition_table/*.bin
